DATE_TIME_FORM = "%Y-%m-%d %H:%M:%S"
USER_ID_1_SAMPLE_JWT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHBpcmVfYXQiOiIyMDIzLTA4LTIwIDExOjM4OjQ3In0.kg8TXPyr2l5aNl8I_1vFny7RNPvwAes3fOfzXr7WZFI"
